"""A distinct source-bound L host using the reviewed graph consumer.

The synthetic host seam is generated by the existing recipe fixture, but its
alternative effect is the exact graph fixture's deterministic merge. The graph
module is copied unchanged and its bytes are checked against the #59 matrix.
"""
from __future__ import annotations

from pathlib import Path
import importlib
import importlib.metadata
import json
import sqlite3
import shutil

import pytest

from jev_integration_evaluator.config import load_config
from jev_integration_evaluator.io import digest, file_hash
from jev_integration_evaluator.scanner import scan_repo
from jev_integration_evaluator.scoring import apply_reviews
from jev_integration_evaluator.integrations.lifecycle import (
    apply_implementation, plan_implementation, rollback_implementation)
from jev_integration_evaluator.integrations.verification import verify_implementation
from jev_integration_evaluator.use_case_templates import use_case_matrix
from scripts.implementation_fixtures import fixture


ROOT = Path(__file__).resolve().parents[1]
GRAPH_RUNTIME_SHA256 = "fc9b0930986d9fba96187f458415de43871a44fdd67e782ee071f9715e8d5364"


def _graph_host(target: Path, version: str | None = None):
    assert version in (None, "1.0.0", "1.0.1")
    inventory, spec = fixture(target, "L", tag="graph_consumer", layout="package",
                              package_name="graph_host")
    package = target / "graph_host"
    graph_source = ROOT / "examples/graph-system/entities.py"
    pinned = next(row["source_sha256"] for row in use_case_matrix()["rows"] if row["id"] == "L")
    assert file_hash(graph_source) == pinned
    shutil.copyfile(graph_source, package / "graph.py")
    assert file_hash(package / "graph.py") == pinned
    runtime_source = ROOT / "examples/use-case-host/graph_runtime.py"
    assert file_hash(runtime_source) == GRAPH_RUNTIME_SHA256
    shutil.copyfile(runtime_source, package / "graph_runtime.py")
    assert file_hash(package / "graph_runtime.py") == GRAPH_RUNTIME_SHA256
    source = target / spec["source"]["file"]
    raw = source.read_text(encoding="utf-8")
    assert raw.count("'revision': 0") == 1
    raw = raw.replace("'revision': 0", "'revision': 0, 'expected_revision': 0", 1)
    primary = "STATE['effects'].append('first')\n    return 'first'"
    primary_bound = ("from . import graph_runtime\n"
                     "    STATE['revision'] = graph_runtime.merge(request, STATE)\n"
                     "    STATE['effects'].append('first')\n"
                     "    return 'first'")
    assert raw.count(primary) == 1
    raw = raw.replace(primary, primary_bound)
    old = "STATE['revision'] += 1\n    return 'merged'"
    new = "from . import graph_runtime\n    STATE['revision'] = graph_runtime.merge(request, STATE)\n    return 'merged'"
    assert raw.count(old) == 1
    source.write_text(raw.replace(old, new), encoding="utf-8")
    for case in spec["verification"]["cases"]:
        case["initial_globals"]["STATE"]["expected_revision"] = 0
        case["request"]["graph_action"] = "reconcile_same"

    if version is not None:
        entry = spec["verification"]["entry_point"]
        (package / "console.py").write_text(
            f"from .{source.stem} import {entry}\n"
            "from pathlib import Path\nimport os\nimport time\n"
            "def main():\n"
            "    request = {'task_id':'graph-task','graph_action':'reconcile_same'}\n"
            f"    {entry}(request)\n"
            "    ready = os.environ.get('GRAPH_READY_PATH')\n"
            "    if ready:\n"
            "        with Path(ready).open('x', encoding='utf-8') as stream:\n"
            "            stream.write('ready\\n')\n"
            "    time.sleep(15)\n"
            "    return 0\n"
            "if __name__ == '__main__':\n    raise SystemExit(main())\n",
            encoding="utf-8")
        tools = {name: importlib.metadata.version(name) for name in ("pip", "setuptools", "wheel")}
        (target / "pyproject.toml").write_text(
            '[build-system]\nrequires = ["setuptools==' + tools["setuptools"] +
            '", "wheel==' + tools["wheel"] + '"]\nbuild-backend = "setuptools.build_meta"\n'
            '[project]\nname = "jev-graph-host-fixture"\nversion = "' + version + '"\n'
            'requires-python = ">=3.13"\n'
            'dependencies = ["jev-integration-evaluator==1.3.0.dev12"]\n'
            '[project.scripts]\ngraph-host = "graph_host.console:main"\n'
            '[tool.setuptools.packages.find]\ninclude = ["graph_host*"]\n', encoding="utf-8")

    cfg = load_config()
    cfg["repository"]["typescript_ast"] = False
    inventory = scan_repo(target, cfg)
    candidate = next(row for row in inventory["candidates"]
                     if row["source"]["symbol"] == "select_boundary_graph_consumer")
    reason = ("Reviewed L host seam: graph merge remains host-owned and requires "
              "approval, exact entity source, current revision and pre-mutation audit")
    apply_reviews(inventory, {candidate["candidate_id"]: {
        "source_sha256": candidate["source"]["source_sha256"],
        "approved": True, "reviewer": "offline-graph-host-author", "reason": reason}}, cfg)
    spec["candidate_id"] = candidate["candidate_id"]
    spec["experiment_id"] = candidate["recommended_experiment"]["id"]
    spec["inventory_sha256"] = digest(inventory)
    spec["inventory_fingerprint"] = inventory["scan_fingerprint"]
    spec["source"].update({
        "file_sha256": candidate["source"]["file_sha256"],
        "source_sha256": candidate["source"]["source_sha256"]})
    spec["binding_review"]["source_sha256"] = candidate["source"]["source_sha256"]
    spec["binding_review"]["reason"] = reason
    return inventory, spec


def test_graph_host_source_bound_apply_verify_and_rollback(tmp_path):
    target = tmp_path / "graph-target"
    inventory, spec = _graph_host(target)
    bundle = tmp_path / "bundle"
    planned = plan_implementation(target, inventory, spec["candidate_id"], spec, bundle)
    effects = tmp_path / "probe-effects"
    effects.mkdir(mode=0o700)
    with pytest.MonkeyPatch.context() as env:
        env.setenv("GRAPH_EFFECT_PATH", str(effects / "graph-{pid}.json"))
        env.setenv("GRAPH_DB_PATH", str(effects / "graph-{pid}.sqlite"))
        baseline = verify_implementation(target, bundle, "baseline", approve_execution=True)
        assert baseline["status"] == "baseline_passed"
        applied = apply_implementation(target, bundle, planned["bundle_digest"],
                                       baseline_sha256=baseline["receipt_sha256"])
        modified = verify_implementation(target, bundle, "modified", approve_execution=True,
                                         baseline_sha256=baseline["receipt_sha256"])
    assert modified["status"] == "verified"
    assert list(effects.glob("graph-*.json"))
    assert rollback_implementation(target, bundle, applied["rollback_digest"])["status"] == "rolled_back"


def test_graph_host_current_revision_and_approval_are_independent(tmp_path, monkeypatch):
    target = tmp_path / "graph-target"
    _graph_host(target)
    monkeypatch.syspath_prepend(str(target))
    runtime = importlib.import_module("graph_host.graph_runtime")
    effects = tmp_path / "effects"
    effects.mkdir(mode=0o700)
    effect = effects / "graph-effect.json"
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effect))
    request = {"task_id": "graph-task", "graph_action": "reconcile_same"}
    with pytest.raises(ValueError, match="finite graph action"):
        runtime.merge({**request, "graph_action": "arbitrary"},
                      {"revision": 4, "expected_revision": 4, "approval": True})
    monkeypatch.delenv("GRAPH_EFFECT_PATH")
    with pytest.raises(ValueError, match="GRAPH_EFFECT_PATH is required"):
        runtime.merge(request, {"revision": 4, "expected_revision": 4,
                                "approval": True})
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effect))
    for state in (
        {"revision": 4, "expected_revision": 3, "approval": True},
        {"revision": 4, "expected_revision": 4, "approval": False},
    ):
        with pytest.raises(RuntimeError, match="graph merge did not satisfy"):
            runtime.merge(request, state)
        assert not effect.exists() and state["revision"] == 4
    assert runtime.merge(request, {"revision": 4, "expected_revision": 4,
                              "approval": True}) == 5
    observed = json.loads(effect.read_text(encoding="utf-8"))
    assert observed["revision"] == 5
    assert observed["receipt"] == observed["merges"][0] == observed["audits"][0]
    assert observed["entities"]["left"]["provenance"] == "registry-left"


def test_graph_sqlite_transaction_and_independent_readback(tmp_path, monkeypatch):
    target = tmp_path / "graph-target"
    _graph_host(target)
    monkeypatch.syspath_prepend(str(target))
    runtime = importlib.import_module("graph_host.graph_runtime")
    effects = tmp_path / "effects"
    effects.mkdir(mode=0o700)
    database = effects / "graph.sqlite"
    monkeypatch.setenv("GRAPH_DB_PATH", str(database))
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effects / "first.json"))
    request = {"task_id": "graph-task", "graph_action": "reconcile_same"}
    state = {"revision": 0, "expected_revision": 0, "approval": True}
    assert runtime.merge(request, state) == 1
    with sqlite3.connect(database.as_uri() + "?mode=ro", uri=True) as observed:
        assert observed.execute("SELECT value FROM revision").fetchall() == [(1,)]
        assert observed.execute("SELECT key, provenance FROM entities ORDER BY key").fetchall() == [
            ("left", "registry-left"), ("right", "registry-right")]
        audit = [json.loads(row[0]) for row in observed.execute("SELECT receipt FROM audit")]
        merges = [json.loads(row[0]) for row in observed.execute("SELECT receipt FROM merges")]
    assert audit == merges == [json.loads((effects / "first.json").read_text())["receipt"]]
    original = database.read_bytes()
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effects / "stale.json"))
    with pytest.raises(RuntimeError, match="revision conflict"):
        runtime.merge(request, state)
    assert database.read_bytes() == original and not (effects / "stale.json").exists()
    with sqlite3.connect(database) as changed:
        changed.execute("UPDATE entities SET name = 'Other' WHERE key = 'left'")
    conflicting = database.read_bytes()
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effects / "conflict.json"))
    with pytest.raises(RuntimeError, match="identity or revision conflict"):
        runtime.merge(request, {"revision": 1, "expected_revision": 1,
                                "approval": True})
    assert database.read_bytes() == conflicting and not (effects / "conflict.json").exists()
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effects / "denied.json"))
    with pytest.raises(RuntimeError, match="host postconditions"):
        runtime.merge(request, {"revision": 1, "expected_revision": 1,
                                "approval": False})
    assert database.read_bytes() == conflicting and not (effects / "denied.json").exists()
    with sqlite3.connect(database) as setup:
        setup.execute("UPDATE entities SET name = 'Acme' WHERE key = 'left'")
        setup.execute("CREATE TRIGGER refuse_audit BEFORE INSERT ON audit "
                      "BEGIN SELECT RAISE(ABORT, 'audit refused'); END")
    before_audit = database.read_bytes()
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effects / "audit-failed.json"))
    with pytest.raises(sqlite3.IntegrityError, match="audit refused"):
        runtime.merge(request, {"revision": 1, "expected_revision": 1,
                                "approval": True})
    assert database.read_bytes() == before_audit
    assert not (effects / "audit-failed.json").exists()
    with sqlite3.connect(database) as setup:
        setup.execute("DROP TRIGGER refuse_audit")
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effects / "recovered.json"))
    assert runtime.merge(request, {"revision": 1, "expected_revision": 1,
                                   "approval": True}) == 2
    with sqlite3.connect(database.as_uri() + "?mode=ro", uri=True) as observed:
        assert observed.execute("SELECT value FROM revision").fetchall() == [(2,)]
        assert observed.execute("SELECT COUNT(*) FROM audit").fetchone() == (2,)
        assert observed.execute("SELECT COUNT(*) FROM merges").fetchone() == (2,)
