"""A distinct source-bound L host using the reviewed graph consumer.

The synthetic host seam is generated by the existing recipe fixture, but its
alternative effect is the exact graph fixture's deterministic merge. The graph
module is copied unchanged and its bytes are checked against the #59 matrix.
"""
from __future__ import annotations

from pathlib import Path
import importlib
import json
import shutil

import pytest

from jev_integration_evaluator.config import load_config
from jev_integration_evaluator.io import digest, file_hash
from jev_integration_evaluator.scanner import scan_repo
from jev_integration_evaluator.scoring import apply_reviews
from jev_integration_evaluator.integrations.lifecycle import (
    apply_implementation, plan_implementation, rollback_implementation)
from jev_integration_evaluator.integrations.verification import verify_implementation
from jev_integration_evaluator.use_case_templates import use_case_matrix
from scripts.implementation_fixtures import fixture


ROOT = Path(__file__).resolve().parents[1]
GRAPH_RUNTIME_SHA256 = "cfaa603585646ff0ff9751dbfc20194f420346ba5781999d909d75395bd688ac"


def _graph_host(target: Path):
    inventory, spec = fixture(target, "L", tag="graph_consumer", layout="package",
                              package_name="graph_host")
    package = target / "graph_host"
    graph_source = ROOT / "examples/graph-system/entities.py"
    pinned = next(row["source_sha256"] for row in use_case_matrix()["rows"] if row["id"] == "L")
    assert file_hash(graph_source) == pinned
    shutil.copyfile(graph_source, package / "graph.py")
    assert file_hash(package / "graph.py") == pinned
    runtime_source = ROOT / "examples/use-case-host/graph_runtime.py"
    assert file_hash(runtime_source) == GRAPH_RUNTIME_SHA256
    shutil.copyfile(runtime_source, package / "graph_runtime.py")
    assert file_hash(package / "graph_runtime.py") == GRAPH_RUNTIME_SHA256
    source = target / spec["source"]["file"]
    raw = source.read_text(encoding="utf-8")
    assert raw.count("'revision': 0") == 1
    raw = raw.replace("'revision': 0", "'revision': 0, 'expected_revision': 0", 1)
    old = "STATE['revision'] += 1\n    return 'merged'"
    new = "from . import graph_runtime\n    STATE['revision'] = graph_runtime.merge(request, STATE)\n    return 'merged'"
    assert raw.count(old) == 1
    source.write_text(raw.replace(old, new), encoding="utf-8")
    for case in spec["verification"]["cases"]:
        case["initial_globals"]["STATE"]["expected_revision"] = 0

    cfg = load_config()
    cfg["repository"]["typescript_ast"] = False
    inventory = scan_repo(target, cfg)
    candidate = next(row for row in inventory["candidates"]
                     if row["source"]["symbol"] == "select_boundary_graph_consumer")
    reason = ("Reviewed L host seam: graph merge remains host-owned and requires "
              "approval, exact entity source, current revision and pre-mutation audit")
    apply_reviews(inventory, {candidate["candidate_id"]: {
        "source_sha256": candidate["source"]["source_sha256"],
        "approved": True, "reviewer": "offline-graph-host-author", "reason": reason}}, cfg)
    spec["candidate_id"] = candidate["candidate_id"]
    spec["experiment_id"] = candidate["recommended_experiment"]["id"]
    spec["inventory_sha256"] = digest(inventory)
    spec["inventory_fingerprint"] = inventory["scan_fingerprint"]
    spec["source"].update({
        "file_sha256": candidate["source"]["file_sha256"],
        "source_sha256": candidate["source"]["source_sha256"]})
    spec["binding_review"]["source_sha256"] = candidate["source"]["source_sha256"]
    spec["binding_review"]["reason"] = reason
    return inventory, spec


def test_graph_host_source_bound_apply_verify_and_rollback(tmp_path):
    target = tmp_path / "graph-target"
    inventory, spec = _graph_host(target)
    bundle = tmp_path / "bundle"
    planned = plan_implementation(target, inventory, spec["candidate_id"], spec, bundle)
    baseline = verify_implementation(target, bundle, "baseline", approve_execution=True)
    assert baseline["status"] == "baseline_passed"
    applied = apply_implementation(target, bundle, planned["bundle_digest"],
                                   baseline_sha256=baseline["receipt_sha256"])
    modified = verify_implementation(target, bundle, "modified", approve_execution=True,
                                     baseline_sha256=baseline["receipt_sha256"])
    assert modified["status"] == "verified"
    assert rollback_implementation(target, bundle, applied["rollback_digest"])["status"] == "rolled_back"


def test_graph_host_current_revision_and_approval_are_independent(tmp_path, monkeypatch):
    target = tmp_path / "graph-target"
    _graph_host(target)
    monkeypatch.syspath_prepend(str(target))
    runtime = importlib.import_module("graph_host.graph_runtime")
    effect = tmp_path / "graph-effect.json"
    monkeypatch.setenv("GRAPH_EFFECT_PATH", str(effect))
    for state in (
        {"revision": 4, "expected_revision": 3, "approval": True},
        {"revision": 4, "expected_revision": 4, "approval": False},
    ):
        with pytest.raises(RuntimeError, match="graph merge did not satisfy"):
            runtime.merge({}, state)
        assert not effect.exists() and state["revision"] == 4
    assert runtime.merge({}, {"revision": 4, "expected_revision": 4,
                              "approval": True}) == 5
    observed = json.loads(effect.read_text(encoding="utf-8"))
    assert observed["revision"] == 5
    assert observed["receipt"] == observed["merges"][0] == observed["audits"][0]
